title: MapRVA
email: maprva@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  We are a group of mapping enthusiasts in Richmond, Virginia who work
  to create and share geospatial data of our city using OpenStreetMap.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://maprva.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github:  MapRVA
mastodon: https://en.osm.town/@maprva
youtube_page: false
instagram: false
twitter: false
facebook: false
linkedin: false

# Build settings
theme: osmus-dogwood
plugins:
  - jekyll-feed
